server:
  port: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/landlords?serverTimezone=GMT
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

landlords:
  frontend-host: localhost:9000
  jwt-secret: 298b8610-6835-4d12-b8ae-efba3dbcccad
