server:
  port: 8085

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/landlords?serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

landlords:
  frontend-host: landlord.pushyzheng.com
  jwt-secret: 298b8610-6835-4d12-b8ae-efba3dbcccad
