server:
  port: 8080

#database:
#  engine: MySQL
#  url: jdbc:mysql://localhost:3306/landlords?serverTimezone=GMT
#  username: root
#  password: 12345678

database:
  engine: SQLite
  url: jdbc:sqlite:db/landlords.sqlite3
  username:
  password:

landlords:
  frontend-host: localhost:9000
  jwt-secret: 298b8610-6835-4d12-b8ae-efba3dbcccad

logging:
  level:
    site.pushy.landlords.dao: debug
